//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpartanHotels.Repository.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelRoom
    {
        public HotelRoom()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int HotelRoomID { get; set; }
        public Nullable<int> HotelID { get; set; }
        public Nullable<int> RoomTypeID { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> TotalRoomCount { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
