//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpartanHotels.Repository.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Queue
    {
        public string ID { get; set; }
        public string ReservationID { get; set; }
        public byte[] request { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
